<?php
// This script and data application were generated by AppGini 23.11
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/mapa.php');
	include_once(__DIR__ . '/mapa_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('mapa');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'mapa';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`mapa`.`ID`" => "ID",
		"`mapa`.`mapa`" => "mapa",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`mapa`.`ID`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`mapa`.`ID`" => "ID",
		"`mapa`.`mapa`" => "mapa",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`mapa`.`ID`" => "ID",
		"`mapa`.`mapa`" => "Mapa",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`mapa`.`ID`" => "ID",
		"`mapa`.`mapa`" => "mapa",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`mapa` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'mapa_view.php';
	$x->TableTitle = 'Mapa';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`mapa`.`ID`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['Mapa', ];
	$x->ColFieldName = ['mapa', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/mapa_templateTV.html';
	$x->SelectedTemplate = 'templates/mapa_templateTVS.html';
	$x->TemplateDV = 'templates/mapa_templateDV.html';
	$x->TemplateDVP = 'templates/mapa_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: mapa_init
	$render = true;
	if(function_exists('mapa_init')) {
		$args = [];
		$render = mapa_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: mapa_header
	$headerCode = '';
	if(function_exists('mapa_header')) {
		$args = [];
		$headerCode = mapa_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: mapa_footer
	$footerCode = '';
	if(function_exists('mapa_footer')) {
		$args = [];
		$footerCode = mapa_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
